#!/usr/bin/env python3
"""Gate the terrain-op ledger proposal, then promote it to ACCEPTED.

Acceptance discipline: design/terrain_ops.proposal.json is generated by
build_terrain_ops.py and is NOT trusted until it passes every gate here.  On a
clean pass this writes design/terrain_ops.current.json (status accepted); on
any failure it exits non-zero and writes nothing.

Gates map directly to the task's acceptance criteria:
  G1  16-row open fan, every row carries all 6 engineered operations
  G2  fan arc is +/-55 deg (110 deg total)  [Open Civic Bowl invariant]
  G3  every visible surface feature has an op_id (or is existing/no-touch)
  G4  the per-row clip mask geometrically contains its cap/tread/riser/
      drainage surfaces, and ADA + stage footprints suppress terrain draw
      -> no grass/terrain can overlap seat caps or tread surfaces
  G5  no default retaining walls: every riser height < wall_trigger_ft
  G6  every constructed surface has a construction material; the material
      manifest carries the clip policy

stdlib + numpy only.  Exit 0 = accepted, 1 = rejected.
"""
from __future__ import annotations

import datetime as _dt
import json
import os
import sys

import numpy as np

import terrace_ops_common as T

PROPOSAL = os.path.join(T.DESIGN_DIR, "terrain_ops.proposal.json")
CURRENT = os.path.join(T.DESIGN_DIR, "terrain_ops.current.json")
ROW_OPS = ("riser", "tread", "cap", "drainage", "transition", "clip_mask")


def _layer(name):
    return T.load_geojson(os.path.join(T.GEO_OUT, f"{name}.geojson"))["features"]


def _ring(feat):
    return feat["geometry"]["coordinates"][0]


def angular_span(points, center):
    az = sorted(T.az_deg(center, p) for p in points)
    if len(az) < 2:
        return 0.0
    gaps = [az[i + 1] - az[i] for i in range(len(az) - 1)]
    gaps.append(360.0 - (az[-1] - az[0]))  # wrap gap
    return 360.0 - max(gaps)


def main():
    fails, notes = [], []

    def check(cond, ok, bad):
        (notes if cond else fails).append((cond, ok if cond else bad))
        print(f"  [{'PASS' if cond else 'FAIL'}] {ok if cond else bad}")

    if not os.path.exists(PROPOSAL):
        print("FAIL: no proposal. Run scripts/build_terrain_ops.py first.")
        return 1
    ledger = T.load_geojson(PROPOSAL)
    center = tuple(ledger["bowl_center_epsg6494"])
    ops = ledger["ops"]
    by_op = {o["op_id"]: o for o in ops}

    print("== G1 16-row open fan, all 6 ops per row ==")
    rows = sorted({o["row"] for o in ops if o.get("kind") in ROW_OPS and o.get("row")})
    check(rows == list(range(1, 17)), "16 rows present (1..16)",
          f"rows != 1..16: {rows}")
    missing = []
    for r in range(1, 17):
        have = {o["kind"] for o in ops if o.get("row") == r and o["kind"] in ROW_OPS}
        if have != set(ROW_OPS):
            missing.append((r, sorted(set(ROW_OPS) - have)))
    check(not missing, "every row carries riser/tread/cap/drainage/transition/clip",
          f"rows missing ops: {missing}")

    print("== G2 fan arc +/-55 deg (110 deg total) ==")
    caps = _layer("seat_caps")
    spans = [angular_span(_ring(f), center) for f in caps]
    span = float(np.median(spans)) if spans else 0.0
    target = T.INVARIANTS["fan_total_angle_deg"]
    check(abs(span - target) <= 12.0,
          f"median fan arc {span:.1f} deg ~ {target} deg (+/-55)",
          f"fan arc {span:.1f} deg deviates from {target} deg")

    print("== G3 every visible surface feature has an op_id ==")
    no_id = []
    for ln in ("seat_caps", "tread_surfaces", "riser_faces", "drainage_bands",
               "terrain_transitions", "ada_paths", "stage_floor"):
        for f in _layer(ln):
            p = f["properties"]
            if not p.get("op_id") or not p.get("surface_class"):
                no_id.append((ln, p.get("op_id")))
    check(not no_id, "all surface features carry op_id + surface_class",
          f"features missing op_id/surface_class: {no_id[:5]}")

    print("== G4 clip masks cover caps/treads/risers/drainage; ADA+stage suppress ==")
    # Exact, robust containment for concentric bands: each constructed surface's
    # radial interval [r_inner, r_outer] must lie within its row clip mask's
    # interval over the same arc sweep. (Vertex-in-polygon is fragile on the
    # shared end-edges of thin curved bands, so radial intervals are the gate;
    # an independent geometric centroid spot-check is reported as a soft signal.)
    TOL = 0.02
    clip_iv = {f["properties"]["row"]:
               (f["properties"]["r_inner_ft"], f["properties"]["r_outer_ft"])
               for f in _layer("clip_mask")}
    surf_iv = {lbl: {f["properties"]["row"]:
                     (f["properties"]["r_inner_ft"], f["properties"]["r_outer_ft"])
                     for f in _layer(ln)}
               for lbl, ln in (("cap", "seat_caps"), ("tread", "tread_surfaces"),
                               ("riser", "riser_faces"), ("drainage", "drainage_bands"))}
    uncovered = []
    for r, (cr0, cr1) in clip_iv.items():
        for lbl, table in surf_iv.items():
            iv = table.get(r)
            if iv is None or iv[0] < cr0 - TOL or iv[1] > cr1 + TOL:
                uncovered.append((r, lbl, iv))
    check(not uncovered,
          "every cap/tread/riser/drainage radial footprint lies inside its row "
          "clip mask (terrain cannot draw over seats or treads)",
          f"surfaces NOT covered by clip mask: {uncovered[:8]}")
    # soft geometric spot-check: an interior radial midpoint sample of each cap
    # band should fall inside its clip ring (reports drift; does not gate)
    miss = 0
    for f in caps:
        r = f["properties"]["row"]
        ring = _ring(f)
        mid = np.asarray(ring[len(ring) // 4], dtype=float)
        clipf = next(c for c in _layer("clip_mask") if c["properties"]["row"] == r)
        if not T.point_in_ring(mid, _ring(clipf)):
            miss += 1
    print(f"  [info] geometric cap-in-clip spot-check: {len(caps) - miss}/{len(caps)} "
          "interior samples inside (radial intervals are the gate)")
    not_suppressed = [f["properties"].get("op_id")
                      for ln in ("ada_paths", "stage_floor")
                      for f in _layer(ln)
                      if f["properties"].get("surface_class") in ("ada", "stage")
                      and not f["properties"].get("suppress_terrain_draw")]
    check(not not_suppressed,
          "all ADA + stage surfaces flagged suppress_terrain_draw",
          f"ADA/stage not suppressing terrain: {not_suppressed}")

    print("== G5 no default retaining walls ==")
    wall = T.INVARIANTS["wall_trigger_ft"]
    tall = [(f["properties"]["row"], f["properties"].get("riser_height_ft"))
            for f in _layer("riser_faces")
            if (f["properties"].get("riser_height_ft") or 0) >= wall]
    maxr = max((f["properties"].get("riser_height_ft") or 0)
               for f in _layer("riser_faces"))
    check(not tall, f"max riser {maxr:.2f} ft < wall trigger {wall} ft (planted slopes)",
          f"riser(s) >= wall trigger {wall} ft: {tall}")

    print("== G6 construction materials + clip policy ==")
    mats = T.material_table()
    bad_mat = [o["op_id"] for o in ops
               if o["surface_class"] in T.CLIPPED_CLASSES
               and o.get("material") not in mats]
    check(not bad_mat, "every constructed surface has a construction material",
          f"ops missing a known material: {bad_mat[:8]}")
    man_path = os.path.join(T.MANIFEST_DIR, "terrace_material_manifest.json")
    has_policy = False
    if os.path.exists(man_path):
        man = T.load_geojson(man_path)
        has_policy = bool(man.get("clip_policy", {}).get("clipped_surface_classes"))
    check(has_policy, "material manifest carries the terrain clip policy",
          "material manifest missing clip_policy")

    print()
    if fails:
        print(f"REJECTED: {len(fails)} gate(s) failed. terrain_ops.current.json NOT written.")
        return 1

    # ---- promote proposal -> accepted -----------------------------------
    ledger["status"] = "accepted"
    for o in ledger["ops"]:
        o["status"] = "accepted"
    ledger["validation"] = {
        "state": "PASS",
        "validated_by": "scripts/validate_terrain_ops.py",
        "date": _dt.date.today().isoformat(),
        "gates": ["G1 16-row+6ops", "G2 fan +/-55", "G3 op_id coverage",
                  "G4 clip covers seats/treads/ada/stage", "G5 no retaining walls",
                  "G6 construction materials + clip policy"],
        "fan_arc_deg": round(span, 1),
        "max_riser_ft": round(maxr, 2),
        "op_count": len(ledger["ops"]),
    }
    with open(CURRENT, "w") as fh:
        json.dump(ledger, fh, indent=1)
    print(f"ACCEPTED: promoted proposal -> {os.path.relpath(CURRENT, T.REPO)}")
    print(f"  fan arc {span:.1f} deg, max riser {maxr:.2f} ft, {len(ops)} ops accepted.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
